#+TITLE:     Symantic Style Sheets
#+DATE:      2016-06-15 Wed
#+PROPERTY: session *scratch*
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: org-templates/level-0.org
#+OPTIONS: ^nil

* Introduction
  This document describes in detail the implementation details of the various web applications which are part of Semantic Style Sheet project. See HLD for a overview of the architecture.
 
* Sub Components of SSS
The overall system for Semantic Style Sheets consists of at least these components:
1. SSS Renarrator Studio or SSSStudio
2. SSS Storage
3. SSS Configurator
  
* Implementation strategy
The overall system has been implemented as a collection of various applications. Each one has been developed in their own seperate releases called r0, r1, r2... The overall system also has been developed in its own s0, s1, s2, ... releases. Literate programming techniques have been used to code and document.

** SSS Renarrator or SSSStudio
The implementation details for the studio are found their own respective release documents. Release 0 material can be found here.

** SSS Storage
Not yet implemented

** SSS Configurator
Not yet implemented


* Known Issues
  - A separate repository for systems related issues which includes
    the cluster and its implementation can be viewed [[https://bitbucket.org/vlead/systems/issues?status%3Dnew&status%3Dopen][here]].
